<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="2" total="4" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="53160" started-at="2022-04-28T17:43:06Z" finished-at="2022-04-28T17:43:59Z">
    <groups>
    </groups>
    <test name="regression" duration-ms="53160" started-at="2022-04-28T17:43:06Z" finished-at="2022-04-28T17:43:59Z">
      <class name="testCases.TC001_initialSignIn">
        <test-method status="PASS" signature="init()[pri:0, instance:testCases.TC001_initialSignIn@5f282abb]" name="init" is-config="true" duration-ms="3203" started-at="2022-04-28T17:43:03Z" finished-at="2022-04-28T17:43:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="PASS" signature="initialSignIn(java.lang.String, java.lang.String)[pri:0, instance:testCases.TC001_initialSignIn@5f282abb]" name="initialSignIn" duration-ms="4078" started-at="2022-04-28T17:43:06Z" finished-at="2022-04-28T17:43:10Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[standard_user]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[secret_sauce]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialSignIn -->
        <test-method status="PASS" signature="flushData()[pri:0, instance:testCases.TC001_initialSignIn@5f282abb]" name="flushData" is-config="true" duration-ms="1" started-at="2022-04-28T17:43:10Z" finished-at="2022-04-28T17:43:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- flushData -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:testCases.TC001_initialSignIn@5f282abb]" name="tearDown" is-config="true" duration-ms="3929" started-at="2022-04-28T17:43:59Z" finished-at="2022-04-28T17:44:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testCases.TC001_initialSignIn -->
      <class name="testCases.TC002_SignUp">
        <test-method status="FAIL" signature="signUp()[pri:0, instance:testCases.TC002_SignUp@167fdd33]" name="signUp" duration-ms="47919" started-at="2022-04-28T17:43:10Z" finished-at="2022-04-28T17:43:58Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Sauce Labs | Get Started Guide] but found [Sign Up for a Free Trial | Sauce Labs]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Sauce Labs | Get Started Guide] but found [Sign Up for a Free Trial | Sauce Labs]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at testCases.TC002_SignUp.signUp(TC002_SignUp.java:74)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signUp -->
        <test-method status="PASS" signature="flushData()[pri:0, instance:testCases.TC002_SignUp@167fdd33]" name="flushData" is-config="true" duration-ms="125" started-at="2022-04-28T17:43:59Z" finished-at="2022-04-28T17:43:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- flushData -->
      </class> <!-- testCases.TC002_SignUp -->
    </test> <!-- regression -->
  </suite> <!-- Suite -->
</testng-results>
